#!/usr/bin/env bash

#check if the argument is not provided
if [ -z "$1" ]; then
    echo "Argument not provided"
else
    export VPC_ID="$1"
fi

if [ -z "$2" ]; then
    echo "Argument not provided"
else
    export IGW_ID="$2"
fi

if [ -z "$3" ]; then
    echo "Argument not provided"
else
    export SUBNET_ID="$3"
fi

# detach the IGW

aws ec2 detach-internet-gateway \
--internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# delete the IGW
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

# delete the Subnet

aws ec2 delete-subnet \
--subnet-id $SUBNET_ID

# delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID

