#!/usr/bin/env bash
echo "== list objects"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api list-objects-v2 \
--bucket $1 \
--query Location \
--output text
