#!/usr/bin/env bash
echo "== put-object"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# where we'll store these filesif [ -z "$2" ]; then
if [ -z "$2" ]; then
    echo "There needs to be a filename prefi eg. ./bucket my-bucket-name my-filename-prefix"
    exit 1
fi
BUCKET_NAME="$1"
FILENAME="$2"
OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY